site_name: Writing Resources

site_author: Kyle Weishaar

site_description: A learning portal for working with git as a source control for Flare documentation

repo_url: https://github.com/kyleweishaar/git-site

theme:
  name: material
  logo: 'assets/favicon.ico'

extra:
  search:
    language: 'en'

extra_css:
  - 'assets/stylesheets/custom-style1.css'
  - 'assets/stylesheets/custom-style.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true

pages:
  - Moving to Git: index.md
  - Download Software:
    - Git: git.md
    - Git Extension: gitextension.md
    - Git LFS: lfs.md
    - Meld: meld.md
  - Set up your repository:
    - Clone the repo: clone.md
    - Set up Artifactory: artifactory.md
    - Get the remote branches: remote.md
  - Tutorials:
    - Working on Files:
      - mergetool: mergetool.md
      - Working on a File in Git Extension: working-gitExt.md
      - Working on a File with Git Bash: working-gitbash.md
    - Branching:
      - About Branches: branches.md
      - Create a Branch with Git Extension: branching_gitExt.md
      - Create a Branch with Git Bash: branch-gitbash.md
      - Git Extension Graph: gitExt-graph.md
      - Branching Best Practices: best-practice-branch.md
    - Merging:
      - Merge with Git Extension: merge-gitExt.md
      - Merge with Git Bash: merge-gitbash.md
    - Building:
        - Run a build in Jenkins: build.md
    - Cherry Pick:
      - Cherry Pick with Git Extension: cherrypick-gitExt.md
    - Blame:
      - Blame with Git Extension: blame-gitExt.md
    - Merge and Rebase:
      - Rebase with Sourcetree: rebase-sourcetree.md
    - Amend Commits:
      - Amend Commits from command line: amend.md
    - Squash Commits:
      - Squash Commits with Git Extension: squash-gitExt.md
      - Squash and Merge with Git Bash: squash_all.md
    - Recover a deleted branch: recover-branch.md
    - Reverse Commits:
      - Revert Commits with Git Extension: revert-gitExt.md
      - Reset Commits with Git Extension: delete-gitExt.md
      - Recover Deleted commits: recover.md
      - Revert merge commits: revert-merge-commit.md
    - Important Concepts:
      - Fetch vs. Pull: fetch-v-pull.md
      - Merge Conflicts: conflicts.md
      - Git log: history.md
  - Sample workflow:
    - Complete Workflow: complete-workflow.md
  - Extras: 
    - Tips for Using Git Bash: commandline-tips.md
    - Git commands: commands.md
    - Git Extension Graph: gitExt-graph.md
    - Git Terminology: terminology.md

  - About this website: about.md